
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewController","number":53,"title":"Create Menu Item Review Controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/53"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-ArticlesController-GET","number":52,"title":"Articles Controller GET endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/52"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-ArticlesController-PUT","number":51,"title":"Articles Controller PUT endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/51"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-ArticlesController-DELETE","number":50,"title":"Articles Controller DELETE endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/50"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-ArticlesController","number":49,"title":"Articles Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/49"}]
