
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-ArticlesController","number":49,"title":"Articles Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/49"},{"author":{"id":"MDQ6VXNlcjMyNDAyOTk3","is_bot":false,"login":"andrew344c","name":"Andrew"},"headRefName":"Andrew-HelpRequestController","number":48,"title":"Create HelpRequests Controller with /all and /post endpoints","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/48"},{"author":{"id":"MDQ6VXNlcjMyNDAyOTk3","is_bot":false,"login":"andrew344c","name":"Andrew"},"headRefName":"Andrew-HelpRequest","number":47,"title":"Help Request Database Creation","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/47"},{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"Anderson-Database","number":45,"title":"UCSBDiningCommonsMenu Database Issue","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/45"}]
