
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-4
pull_requests: [{"author":{"id":"U_kgDOBdLvhw","is_bot":false,"login":"andersonlee3","name":""},"headRefName":"Anderson-Put","number":65,"title":"implemented put endpoint and passed tests for menu items","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/65"},{"author":{"id":"U_kgDOB0-GGg","is_bot":false,"login":"JLowe32","name":""},"headRefName":"Jaren-RecRequestController-PUT","number":63,"title":"Jaren-Controller Added All Methods ","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/63"}]
