
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-4
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewDelete","number":59,"title":"Create Menu Item Review GET","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/59"},{"author":{"id":"MDQ6VXNlcjE3MTAzNzkw","is_bot":false,"login":"WinbertZhang","name":"Winbert Zhang"},"headRefName":"Winbert-MenuItemReviewGet","number":58,"title":"Create Menu Item Review GET","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/58"},{"author":{"id":"U_kgDOCEeAFA","is_bot":false,"login":"emrecikisir","name":"Emre Cikisir"},"headRefName":"Emre-Organization","number":57,"title":"Organizations Database Creation","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/57"},{"author":{"id":"MDQ6VXNlcjMyNDAyOTk3","is_bot":false,"login":"andrew344c","name":"Andrew"},"headRefName":"Andrew-HelpRequestControllerPut","number":56,"title":"Add HelpRequest PUT Endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/56"},{"author":{"id":"MDQ6VXNlcjQ2MDk1NTAw","is_bot":false,"login":"tihdiR","name":""},"headRefName":"Ridhit-ArticlesController-GET","number":52,"title":"Articles Controller GET endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-4/pull/52"}]
